name: 'Branch Issue'
description: 'Get the issue associated with the branch'

inputs:
  # input-1:
  #   description: Input description.
  #   required: false
  #   default: default-value
  # input-2:
  #   description: Input description.
  #   required: false
  #   default: default-value
  # input-3:
  #   description: Input description.
  #   required: false
  #   default: default-value
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Extract issue number from branch
      id: extract-issue
      shell: bash
      run: |
        BRANCH="${GITHUB_REF##*/}"
        ISSUE_NO=$(echo $BRANCH|cut -d"-" -f1| cut -d"." -f2)

        echo "Found issue number: $ISSUE_NO"
        echo "Branch: $BRANCH"
        echo "Issue No: $ISSUE_NO"
        echo "issue-number=$ISSUE_NO" >> $GITHUB_OUTPUT
        echo "issue-exists=true" >> $GITHUB_OUTPUT

    - name: Check if GitHub issue exists
      id: issue-exists
      shell: bash
      if: steps.extract-issue.outputs.issue-exists == 'true'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        REPO="${{ github.repository }}"
        ISSUE_NO=${{ steps.extract-issue.outputs.issue-number }}
        ISSUE_NO=123
        
        STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/$REPO/issues/$ISSUE_NO)
        
        if [ "$STATUS_CODE" -eq 200 ]; then
          echo "✅ Issue #$ISSUE_NO exists in $REPO"
        else
          echo "❌ Issue #$ISSUE_NO does NOT exist in $REPO (HTTP $STATUS_CODE)"
        fi
